# Site settings
name: Vpromise's Blog
email: vpromisever@gmail.com
author: vpromise
url: https://vpromisever.github.io
resume_site: https://vpromisever.github.io
github: https://github.com/vpromisever
baseurl: # github pages
description: keep making magic!
meta_description: It's vpromise. keep making magic!
motto: keep making magic!
banner: keep making magic!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: vpromisever

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

